feat: initial commit
terraform-ibm-modules/terraform-ibm-data-engine pull request #1
Opened 2023-05-04 08:47 UTC by Aayush-Abhyarthi

### Description

Migrate Data Engine module to TIM

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-05-04 11:35 UTC, ocofaigh requested changes
see comments

2023-05-04 11:35 UTC, ocofaigh commented on variables.tf
> +variable "key_protect_root_key" {
rename the variable to `kms_key_crn` since the module will support key protect or hyper protect

2023-05-04 11:35 UTC, ocofaigh commented on variables.tf
> +  description = "(Optional) Id of existing key to be used"
(Optional) The root key CRN of a Key Management Service like Key Protect or Hyper Protect Crypto Service (HPCS) that you want to use for disk encryption. If `null`, database is encrypted by using randomly generated keys. See https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-key-protect&interface=ui#key-byok for current list of supported regions for BYOK

2023-05-04 11:35 UTC, ocofaigh commented on variables.tf
> +variable "key_protect_guid" {
key_protect_guid -> existing_kms_instance_guid

2023-05-04 11:35 UTC, ocofaigh commented on variables.tf
> +  description = "(Optional) Guid of existing key protect to be used"
The GUID of the Hyper Protect or Key Protect instance in which the key specified in var.kms_key_crn is coming from. Only required if skip_iam_authorization_policy is false

2023-05-04 11:35 UTC, ocofaigh commented on variables.tf
> +variable "key_protect_region" {
Do we really need? Doesn't the KMS instance also have to be in the same region as the data engine instance anyway (double check this)? So the region variable should suffice here?

2023-05-04 11:35 UTC, ocofaigh commented on main.tf
> +      "url"  = "https://${var.key_protect_region}.kms.cloud.ibm.com"
what about private endpoint?

2023-05-04 11:35 UTC, ocofaigh commented on examples/complete/main.tf
> +  source                    = "git::https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive.git?ref=v3.1.2"
can you use the latest version of `terraform-ibm-key-protect-all-inclusive` - that way you can remove the restapi provider completely from the example.

2023-05-04 11:35 UTC, ocofaigh commented on README.md
> +  key_protect_root_key = var.key_protect_root_key
can you update the usage to have real like values here instead of variables. That way consumers can see what the expected format for each of the variable values.

2023-05-04 11:35 UTC, ocofaigh commented on .secrets.baseline
> +      "ghe_instance": "github.com",
this should remain at github.ibm.com

2023-05-04 11:35 UTC, ocofaigh commented on .github/workflows/ci.yml
> +      craTarget: "examples/complete"
Can you update this to use SCCv2:

1. Update `.github/workflows/ci.yml` (see [example](https://github.com/terraform-ibm-modules/terraform-ibm-icd-mongodb/blob/main/.github/workflows/ci.yml))
2. If there are any failures address them, otherwise add them to a file called `cra-tf-validate-ignore-rules.json` (see [example](https://github.com/terraform-ibm-modules/terraform-ibm-icd-mongodb/blob/main/cra-tf-validate-ignore-rules.json))
3. Delete `cra-tf-validate-ignore-goals.json`

2023-05-04 11:36 UTC, ocofaigh commented on variables.tf
> +  description = "(Optional) Id of existing key to be used"
Hmm, actually data engine is not an ICD service, so perhaps find the relevant docs for data engine and use instead

2023-05-04 11:37 UTC, ocofaigh requested changes
I also notice the module is missing the code to create the KMS auth policy (and the variable `skip_iam_authorization_policy` to skip creating it). Can you add please?

2023-05-08 19:06 UTC, ocofaigh commented
@Aayush-Abhyarthi no point in rebasing the PR (which kicks off the pipeline tests and provisions things in our account) until PR comments have been addressed

2023-05-09 09:14 UTC, Aayush-Abhyarthi commented on variables.tf
> +variable "key_protect_root_key" {
done

2023-05-09 09:14 UTC, Aayush-Abhyarthi commented on variables.tf
> +  description = "(Optional) Id of existing key to be used"
added

2023-05-09 09:14 UTC, Aayush-Abhyarthi commented on variables.tf
> +  description = "(Optional) Guid of existing key protect to be used"
added

2023-05-09 09:16 UTC, Aayush-Abhyarthi commented on variables.tf
> +variable "key_protect_region" {
[https://github.ibm.com/GoldenEye/data-engine-module/pull/19#discussion_r6945206](url)

2023-05-09 09:16 UTC, Aayush-Abhyarthi commented on main.tf
> +      "url"  = "https://${var.key_protect_region}.kms.cloud.ibm.com"
added

2023-05-09 09:16 UTC, Aayush-Abhyarthi commented on examples/complete/main.tf
> +  source                    = "git::https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive.git?ref=v3.1.2"
updated

2023-05-09 09:16 UTC, Aayush-Abhyarthi commented on README.md
> +  key_protect_root_key = var.key_protect_root_key
updated

2023-05-09 09:16 UTC, Aayush-Abhyarthi commented on .github/workflows/ci.yml
> +      craTarget: "examples/complete"
added

2023-05-09 09:35 UTC, Aayush-Abhyarthi commented on .secrets.baseline
> +      "ghe_instance": "github.com",
updated

2023-05-10 10:55 UTC, ocofaigh requested changes
see comments

2023-05-10 10:55 UTC, ocofaigh commented on variables.tf
> +  description = "(Optional) The root key CRN of a Key Management Service like Key Protect or Hyper Protect Crypto Service (HPCS) that you want to use for disk encryption. If null, database is encrypt
Hyper Protect (HPCS) is not actually supported by Data Engine, so please update this description

2023-05-10 10:55 UTC, ocofaigh commented on variables.tf
> +  description = "Set to true to skip the creation of an IAM authorization policy"
Needs to be more specific:
Set to true to skip the creation of an IAM authorization policy that permits all Data Engine instances in the given resource group to read the encryption key from the KMS instance provided in 'existing_kms_instance_guid'

2023-05-10 10:55 UTC, ocofaigh commented on tests/pr_test.go
> +func TestRunDefaultExample(t *testing.T) {
Rename this to `TestRunBasicExample` after updating the example to `basic` and move it to other_test.go

2023-05-10 10:55 UTC, ocofaigh commented on main.tf
> +  kms_service = var.kms_key_crn != null ? (
no need for any of this logic, hyper protect is not supported

2023-05-10 10:55 UTC, ocofaigh commented on main.tf
> +  count                       = var.skip_iam_authorization_policy ? 0 : 1
this will need to be updated (see https://github.ibm.com/GoldenEye/icd-redis-module/pull/156#discussion_r7475493)

2023-05-10 10:55 UTC, ocofaigh commented on examples/default/variables.tf
> +variable "plan" {
I would remove plan here and allow this example to use the default value

2023-05-10 10:55 UTC, ocofaigh commented on examples/default/outputs.tf
> +  value       = module.data_engine.guid
guid and id can be different things. Perhaps create an output for both, as well as crn

2023-05-10 10:55 UTC, ocofaigh commented on examples/default/README.md
> +# Default Example With Lite Plan
Rename this to `Basic example` and also update the directory name to `examples/basic`

2023-05-10 10:55 UTC, ocofaigh commented on examples/complete/main.tf
> +}
The main module supports creating this auth policy, so you dont need to have it here too

2023-05-10 10:55 UTC, ocofaigh commented on examples/complete/README.md
> + - Create a new resource group if one is not passed in.
missing points about creating key protect instance and root key

2023-05-10 10:55 UTC, ocofaigh commented on README.md
> +This module provisions data engine instance with key protect
This module does not support provisioning key protect?

2023-05-11 21:56 UTC, Aayush-Abhyarthi commented on .github/workflows/ci.yml
> +      craEnvironmentVariables: "TF_VAR_existing_at_instance_crn=crn:v1:bluemix:public:logdnaat:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:b1ef3365-dfbf-4d8f-8ac8-75f4f84d6f4a::,TF_VAR_existing_kms_inst
Removed

2023-05-11 21:56 UTC, Aayush-Abhyarthi commented on .github/settings.yml
> +  description: "Provision data engine instance with key protect"
Changed

2023-05-11 21:56 UTC, Aayush-Abhyarthi commented on README.md
> +To set up your local development environment, see [Local development setup](https://github.ibm.com/GoldenEye/documentation/blob/master/local-dev-setup.md) in the project documentation.
Fixed

2023-05-11 21:57 UTC, Aayush-Abhyarthi commented on README.md
> +}
removed

2023-05-11 21:57 UTC, Aayush-Abhyarthi commented on README.md
> +This module provisions data engine instance with key protect
Changed

2023-05-11 21:58 UTC, Aayush-Abhyarthi commented on examples/complete/README.md
> + - Create a new data engine with new key protect instance in the resource group and region provided.
changed

2023-05-11 21:58 UTC, Aayush-Abhyarthi commented on examples/complete/README.md
> + - Create a new resource group if one is not passed in.
Added

2023-05-11 21:59 UTC, Aayush-Abhyarthi commented on examples/complete/README.md
> +# Complete Example With Standard Plan
Changed

2023-05-11 21:59 UTC, Aayush-Abhyarthi commented on examples/complete/main.tf
> +}
Removed

2023-05-11 21:59 UTC, Aayush-Abhyarthi commented on examples/default/outputs.tf
> +  value       = module.data_engine.guid
Done

2023-05-11 22:00 UTC, Aayush-Abhyarthi commented on examples/default/variables.tf
> +variable "plan" {
Removed

2023-05-11 22:00 UTC, Aayush-Abhyarthi commented on main.tf
> +  count                       = var.skip_iam_authorization_policy ? 0 : 1
Updated

2023-05-11 22:00 UTC, Aayush-Abhyarthi commented on main.tf
> +  kms_service = var.kms_key_crn != null ? (
Removed

2023-05-11 22:00 UTC, Aayush-Abhyarthi commented on tests/pr_test.go
> +func TestRunDefaultExample(t *testing.T) {
Done

2023-05-11 22:00 UTC, Aayush-Abhyarthi commented on variables.tf
> +    condition     = contains(["public", "private"], var.service_endpoints)
Added

2023-05-11 22:01 UTC, Aayush-Abhyarthi commented on variables.tf
> +  default     = "public"
Updated

2023-05-11 22:01 UTC, Aayush-Abhyarthi commented on variables.tf
> +  description = "Set to true to skip the creation of an IAM authorization policy"
Added

2023-05-11 22:01 UTC, Aayush-Abhyarthi commented on variables.tf
> +  description = "(Optional) The root key CRN of a Key Management Service like Key Protect or Hyper Protect Crypto Service (HPCS) that you want to use for disk encryption. If null, database is encrypt
Updated

2023-05-11 22:01 UTC, Aayush-Abhyarthi commented on variables.tf
> +  description = "The GUID of the Hyper Protect or Key Protect instance in which the key specified in var.kms_key_crn is coming from. Only required if skip_iam_authorization_policy is false"
Updated

2023-05-15 08:48 UTC, ocofaigh commented on variables.tf
> +variable "skip_iam_authorization_policy" {
We have decided to go with 1 extra bool variable called `kms_encryption_enabled` so that we can default the `skip_iam_authorization_policy` variable to `false`. Please take a look at the changes in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/186 and update this PR to be the same. Thanks

2023-05-15 08:48 UTC, ocofaigh requested changes
See https://github.com/terraform-ibm-modules/terraform-ibm-data-engine/pull/1/files#r1193529043

2023-05-15 08:48 UTC, ocofaigh requested changes
See https://github.com/terraform-ibm-modules/terraform-ibm-data-engine/pull/1/files#r1193529043

2023-05-19 15:16 UTC, ocofaigh commented
@Aayush-Abhyarthi We found a bug with auto scale config. Please incorporate the fix into this PR. See https://github.com/terraform-ibm-modules/terraform-ibm-icd-mongodb/pull/163 for exact code change to make

2023-05-22 11:40 UTC, ocofaigh submitted a review, later dismissed
Pushed some final cleanups to this branch so it is consistent with other modules. Approving for merge so we can get the first release out. There are some gaps we need to fill such as support for CBRs and service credentials, but I'll create follow on issues for those.

2023-05-22 11:41 UTC, ocofaigh approved these changes

2023-05-22 12:12 UTC, ocofaigh approved these changes

2023-05-22 12:12 UTC, merged

2023-05-22 12:17 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-data-engine/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: