add-cbr-module
terraform-ibm-modules/terraform-ibm-data-engine pull request #10
Opened 2023-05-24 08:49 UTC by Aayush-Abhyarthi

### Description

add-cbr-module
### Types of changes in this PR

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-05-25 07:10 UTC, Khuzaima05 approved these changes

2023-05-25 07:54 UTC, ocofaigh commented on examples/complete/main.tf
> +
You have created a CBR zone, but you never passed any BCR rule to the data engine module?

2023-05-25 07:56 UTC, ocofaigh requested changes
Please update the `examples/complete/README.md` file. Update the title to `Complete example with BYOK encryption and CBR rules` and also add a bullet point saying:
- A context-based restriction (CBR) rule to only allow Data Engine to be accessible from within the VPC.

2023-05-26 10:52 UTC, Aayush-Abhyarthi commented
Data engine does not support CBR...?
[https://cloud.ibm.com/docs/account?topic=account-context-restrictions-whatis#cbr-adopters](url)

2023-05-26 10:59 UTC, ocofaigh commented
@Aayush-Abhyarthi Lets try and find out internally when support will be added

2023-07-26 08:31 UTC, ocofaigh commented
Data engine does not support CBR yet so closing this PR. Keep an eye on updates in https://github.com/terraform-ibm-modules/terraform-ibm-data-engine/issues/9

2023-07-26 08:31 UTC, closed without merging